package sorocaba.peteca.com.simuladorcircuito;

class Resultados {
    // CLASSE QUE CONTEM TODAS AS INFORMAÇOES SOBRE O MÉTODO
    //TODO: POR ENQUANTO, FICA MEIO CAOTICO O MODO DE COMO IMPLEMENTAR E, JÁ PENSANDO
    // EM COMO FAZER AS "FIACAO" PARA FINALIZAR O APLICATIVO.


}
